add-fstab

diff --git a/helpers/system/add-fstab b/helpers/system/add-fstab
--- a/helpers/system/add-fstab
+++ b/helpers/system/add-fstab
@@ -1,41 +1,40 @@
 #!/bin/bash
 
 display_help() {
-  echo "Usage: $0 <device_name> <filesystem_type> <directory_name>"
-  echo "Example: $0 sdb1 ext4 mydrive"
-  exit 1
+    echo "Usage: $0 <device_name> <filesystem_type> <mount_path>"
+    echo "Example: $0 sdb1 ext4 mydrive"
+    exit 1
 }
 
 # Check if no arguments passed or help option provided
 if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-  display_help
+    display_help
 fi
 
 # Check for the correct number of arguments
 if [ $# -ne 3 ]; then
-  echo "Error: Incorrect number of arguments."
-  display_help
+    echo "Error: Incorrect number of arguments."
+    display_help
 fi
 
 device_name="$1"
 filesystem_type="$2"
-directory_name="$3"
-mount_point="/home/$USER/mnt"
-device="/dev/$device_name"
+mount_path="$3"
+device="$device_name"
 uuid=$(lsblk $device -o UUID --noheadings)
 
 if grep -q "UUID=$uuid" /etc/fstab; then
-  echo "UUID $uuid is already present in /etc/fstab. Exiting."
-  exit 1
+    echo "UUID $uuid is already present in /etc/fstab. Exiting."
+    exit 1
 fi
 
-fstab_entry="UUID=$uuid $mount_point/$directory_name $filesystem_type defaults 0 0"
+fstab_entry="UUID=$uuid $mount_path $filesystem_type defaults 0 0"
 echo "$fstab_entry"
 
 read -p "Do you want to add this entry to /etc/fstab? (y/N): " response
 if [[ "$response" =~ ^[Yy]$ ]]; then
-  echo "$fstab_entry" | sudo tee -a /etc/fstab > /dev/null
-  echo "Entry added to /etc/fstab."
+    echo "$fstab_entry" | sudo tee -a /etc/fstab >/dev/null
+    echo "Entry added to /etc/fstab."
 else
-  echo "Operation cancelled by user."
+    echo "Operation cancelled by user."
 fi
